spring.application.name=spring-library
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Porta do servidor (opcional)
server.port=8080
jdbc:postgresql://db.lbhovnmfxhtrhacxbzmg.supabase.co:5432/postgres
postgres
Lilu#01347952